
<section class="onedark boxbg pt7 pb3 bordered rounded-2xl">
<pre>
<span class="onedark LineNr">  </span><span class="onedark LineNr">  1 </span><span class="onedark -tag-delimiter">&lt;</span><span class="onedark -tag">span</span> <span class="onedark -tag-attribute">class</span><span class="onedark -operator">=</span><span class="onedark -string">&quot;badge-sm&quot;</span><span class="onedark -tag-delimiter">&gt;</span><span class="onedark -none"><span class="onedark -spell">Size sm</span></span><span class="onedark -tag-delimiter">&lt;/</span><span class="onedark -tag">span</span><span class="onedark -tag-delimiter">&gt;</span>
<span class="onedark LineNr">  </span><span class="onedark LineNr">  2 </span><span class="onedark -tag-delimiter">&lt;</span><span class="onedark -tag">span</span> <span class="onedark -tag-attribute">class</span><span class="onedark -operator">=</span><span class="onedark -string">&quot;badge-secondary-md&quot;</span><span class="onedark -tag-delimiter">&gt;</span><span class="onedark -none"><span class="onedark -spell">Size md</span></span><span class="onedark -tag-delimiter">&lt;/</span><span class="onedark -tag">span</span><span class="onedark -tag-delimiter">&gt;</span>
<span class="onedark LineNr">  </span><span class="onedark LineNr">  3 </span><span class="onedark -tag-delimiter">&lt;</span><span class="onedark -tag">span</span> <span class="onedark -tag-attribute">class</span><span class="onedark -operator">=</span><span class="onedark -string">&quot;badge-secondary-lg&quot;</span><span class="onedark -tag-delimiter">&gt;</span><span class="onedark -none"><span class="onedark -spell">Size lg</span></span><span class="onedark -tag-delimiter">&lt;/</span><span class="onedark -tag">span</span><span class="onedark -tag-delimiter">&gt;</span>
<span class="onedark LineNr">  </span><span class="onedark LineNr">  4 </span><span class="onedark -tag-delimiter">&lt;</span><span class="onedark -tag">span</span> <span class="onedark -tag-attribute">class</span><span class="onedark -operator">=</span><span class="onedark -string">&quot;badge-surface-xl&quot;</span><span class="onedark -tag-delimiter">&gt;</span><span class="onedark -none"><span class="onedark -spell">Size xl</span></span><span class="onedark -tag-delimiter">&lt;/</span><span class="onedark -tag">span</span><span class="onedark -tag-delimiter">&gt;</span>

</pre>
</section>
