
name: Deploy to hazeui.github.io

on:
  push:
    branches: [main]
    paths:
      - 'website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build website
        run: cd website && bun run build

      - name: Deploy to hazeui.github.io repo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: hazeui/hazeui.github.io
          branch: main
          folder: website/build
          token: ${{ secrets.HAZEUI_SITE_TOKEN }}
          clean: true
