name: Deploy to hazeui.github.io

on:
  push:
    branches: [dev]
    paths:
      - 'website/**'
      - 'packages/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        
      - name: Setup Neovim & generate codedemo components
        run: cd website && bun run setup-nvim

      - name: Build website
        run: cd website && bun run build

      - name: ls
        run: cd website && ls
