name: Deploy website to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'website/**'

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies (monorepo root)
        run: bun install

      - name: Build website
        run: cd website && bun run build

      - name: Copy site to temp dir
        run: |
          mkdir -p temp
          cp -r website/build/* temp/
          touch temp/.nojekyll

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./temp
          publish_branch: gh-pages
