name: Deploy to hazeui.github.io

on:
  push:
    branches: [main]
    paths:
      - 'website/**'
      - 'packages/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Setup Neovim & generate codedemo components
        run: cd website && bun run setup-nvim

      - name: Build website
        run: cd website && bun run build

      - name: Push to hazeui.github.io
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git clone https://x-access-token:${{ secrets.HAZEUI_SITE_TOKEN }}@github.com/hazeui/hazeui.github.io.git site-deploy

          rm -rf site-deploy/*
          cp -r website/build/* site-deploy/

          cd site-deploy
          git add .
          git commit -m "Deploy website $(date +'%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"
          git push
